apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-nfs
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-nfs
  template:
    metadata:
      labels:
        app: guestbook-ui-nfs
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs-vol
          mountPath: /var/nfs # The mountpoint inside the container
      volumes:
      - name: nfs-vol
        nfs:
          server: 10.71.2.10 # IP to our NFS server
          path: /Kubernetes-NFS-Share # The exported directory
